### ISSUE TITLE
Bug sa fetchanjem predmeta u školskoj godini

### ISSUE THREAD

**Issue by Andre-404** [JakovGlavac/eduo-ocjene-docs#1]
Šaljem GET request na ovaj url: `https://ocjene.eduo.help/api/scrape/subjects/5155024030`(classID je uzet iz userInfo-a) i jedini header koji sam stavio je `eduoToken` no kao response dobivam:  `404: This page could not be found` .

**Comment by Andre-404** [comment]
Nakon daljenjeg testiranja potvrdio sam da mogu fetchati bilješke, izostanke, testove i informacije o ponašanju, jedino predmete(a time i ocjene iz predmeta) ne mogu.

**Comment by JakovGlavac** [comment]
Bok Andre,
kako bi dobio id predmeta ideš na `https://ocjene.eduo.help/api/scrape/class/${classId}`  (krivo je pisalo u docs jbg sorry bio sam to mjenjal iz nekog razloga).

BTW na čemu radiš? e ak nađeš još koju grešku javi.

**Comment by Andre-404** [comment]
> BTW na čemu radiš? e ak nađeš još koju grešku javi.

Hvala na brzom odgovoru! Mislim da sam našao jos jednu grešku, ukoliko pokušam dobiti ocjene iz nekog predmeta(pokušavam viditi prošlogodišnje ocjene) dobivam empty array `{"data" : [ ]}`.

Radim na mobilnoj aplikaciji u kojoj želim kombinirati e dnevnik i raspored sati(koji nadem na edupage-u škole) u jednu aplikaciju tako da korisnik moze odmah vidjeti koje sate ima te ukoliko ima neki ispit taj dan/tjedan.
