### ISSUE TITLE
Bug sa ocjenama

### ISSUE THREAD

**Issue by Andre-404** [JakovGlavac/eduo-ocjene-docs#2]
(odlučio sam otvoriti novi issue za ovo pošto je prijašnji issue closed)
> BTW na čemu radiš? e ak nađeš još koju grešku javi.

Hvala na brzom odgovoru! Mislim da sam našao jos jednu grešku, ukoliko pokušam dobiti ocjene iz nekog predmeta(pokušavam viditi prošlogodišnje ocjene) dobivam empty array `{"data" : [ ]}`.

Radim na mobilnoj aplikaciji u kojoj želim kombinirati e dnevnik i raspored sati(koji nadem na edupage-u škole) u jednu aplikaciju tako da korisnik moze odmah vidjeti koje sate ima te ukoliko ima neki ispit taj dan/tjedan.

**Comment by JakovGlavac** [comment]
E da, to tehnički nije bug jer samo je eDnevnik glupo napravljen. Jer gle:

https://user-images.githubusercontent.com/34971091/191036112-dc6701e5-c655-453a-8465-2d0f8e15f528.mp4

Ugl gle ak oćeš dobit ocjene iz prošlogodišnjeg predmeta moraš prvo izlistat predmete prošle godine (tj stavit prošlu godinu kao odabranu) i onda možeš uzimat ocjene iz predmeta. Da to je mutavo; sjećam se da sam gledal dali da napravim da za dobit ocjenu treba i id godine jer onda bi to ja napravil u pozadini na serveru, al mislio sam kao da onda u tom slučaju moraš negdje u aplikaciji pamtit godinu cijelu vrijeme. 

> Radim na mobilnoj aplikaciji u kojoj želim kombinirati e dnevnik i raspored sati(koji nadem na edupage-u škole) u jednu aplikaciju tako da korisnik moze odmah vidjeti koje sate ima te ukoliko ima neki ispit taj dan/tjedan.

To je cool, kaj je najbolje ja sam započeo bio nešto slično. 

BTW u čemu radiš to? 
e i jel koristiš [eduo instukcije](https://instukcije.eduo.help)

**Comment by Andre-404** [comment]
> Ugl gle ak oćeš dobit ocjene iz prošlogodišnjeg predmeta moraš prvo izlistat predmete prošle godine (tj stavit prošlu godinu kao odabranu) i onda možeš uzimat ocjene iz predmeta. 

Ok nije problem, samo nisam kuzio zas ne radi, u tom slucaju cu loadat godinu kada ju user promjeni.

> BTW u čemu radiš to? e i jel koristiš [eduo instukcije](https://instukcije.eduo.help)

Posto zelim deployat na android i ios odlucio sam se za [flutter](https://flutter.dev/) koji koristim sa android studijem, a sto je eduo-a tice ne koristim jer iskreno nisam ni znao da postoji do jucer xD ali malo sam pogledao i jako mi se svida layout i theme websitea(siva sa akcentima plave mi je jedna od najdrazih boja), mozda kad budem imao vremena odgovorim na koje pitanje iz fizike/matematike :)

Malo mi je tesko komunicirat preko github issuesa, pa ako hoces da nastavimo razgovor(a i da mogu brze reportat neke bugove) evo mog discorda: Andre_404#4685

**Comment by JakovGlavac** [comment]
![image](https://user-images.githubusercontent.com/34971091/191044667-fbcf6471-d6ad-42b7-8a8b-e570f1cc092c.png)

Moj discord: Alfa#1212
