### ISSUE TITLE
Problem sa API-em

### ISSUE THREAD

**Issue by Doda94** [JakovGlavac/eduo-ocjene-docs#8]
Bok!
Do prije neki dan mi je login u aplikaciji radio normalno, ovaj tjedan sam primjetio da vise ne radi. Prvo mi je izbacivao error code 500, a sada ne mogu ni poslati request odnosno samo timeouta. Mozes li provjeriti je li sve ok i radi li API normalno s tvoje strane?

Hvala unaprijed 😃!

Ovo dobijem u logcatu u android studiu, ako ti to pomaze 😉:
![image](https://user-images.githubusercontent.com/56204086/209201834-0e5e9367-b3bf-415d-8eaf-b1d1a3fc6f75.png)
![image](https://user-images.githubusercontent.com/56204086/209201873-3b5f4185-f9c7-429e-b4f8-7577982cf6e1.png)

**Comment by JakovGlavac** [comment]
Hmm, gledam i sve bi trebalo raditi.
Rado bi probao logirat se sa svojim računom ali ja više nisam učenik, tako da nemam pristup ednevniku.

Ako fkt misliš da je do mene neki problem dodaj me na discord (Alfa#1212) pa možemo skupa debug-at.

**Comment by Doda94** [comment]
Uf, sad sorry sto kasnim sa odgovorom.
U meduvremenu se popravilo i sad sve radi, nice 😄.

Budem te dodao na discord radi buducih pitanja, mislim da nam je obojici lakse tako nego preko issuesa :).
