### ISSUE TITLE
Ne moze dohvatiti host name

### ISSUE THREAD

**Issue by Malimici** [JakovGlavac/eduo-ocjene-docs#9]
Kad pokusavam poslati request dobijem error:

![error](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/85be2cf0-674a-4511-858c-7be6a3cd1692)

![drugierror](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/9214a04d-c4fe-49fd-a3dc-6951069af4bd)

**Comment by JakovGlavac** [comment]
Da više ne plaćam domenu ta

**Comment by JakovGlavac** [comment]
Da više ne plaćam domenu tako da moraš koristiti `https://eduo-ocjene.fly.dev/` ili direktno preko ip adrese 
`213.188.208.106`. Ako ti se da možeš fixat dokumentaciju i napravit pull request.

**Comment by Malimici** [comment]
Sada mi daje ovaj error:

![drugierror](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/ca3bed76-c2f9-4d82-915b-82599ca17e56)
![error](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/4712448e-11f1-43fd-adf3-06fd053e9d1c)

**Comment by JakovGlavac** [comment]
Jesi probao koristit eduo-ocjene.fly.dev?

**Comment by Malimici** [comment]
Da, ali mi daje error 500: Internal Server Error.

ovo je moj request:

`curl --location '213.188.208.106/api/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username":"Primjer@skole.hr", "password":"Password123"
}'`

ovo je error:

![drugierror](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/51f1c496-8feb-4000-9ac7-901f21f6761c)

**Comment by Malimici** [comment]
ovo je sa eduo-ocjene.fly.dev

![image](https://github.com/JakovGlavac/eduo-ocjene-docs/assets/140530190/464364ac-9107-400e-b29f-b0e5000d43cb)

request:
`curl --location 'eduo-ocjene.fly.dev/api/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username":"Primjer@skole.hr", "password":"Password123"
}'`
